### ISSUE TITLE
Is the param "name_as" still used?

### ISSUE THREAD

**Issue by rspt** [agilare/ladecadanse#34]
Is the param "name_as" still used? It seems like it isn't. Should we remove it?

This param is actually used here:
- ajouterEvenement.php
- contacteznous.php
- footer.php (search form)
- header.php (search form)
- inscription.php
- motdepasse.php
- recherche.php

**Comment by agilare** [comment]
The "as" is for antispam, it's a basic protection against boots.
Trivial boots would fill this field (and real users not, it's hidden). A verification is done server side and if this field is filled, the request will be rejected.

**Comment by rspt** [comment]
Ok thanks!
