### ISSUE TITLE
Sometimes Google map of place location is not displayed

### ISSUE THREAD

**Issue by agilare** [agilare/ladecadanse#42]
In pages [Lieu](https://ladecadanse.darksite.ch/lieu.php?idL=54) and [Événement](https://ladecadanse.darksite.ch/evenement.php?idE=331989) clicking on the "Voir sur le plan" link shows nothing instead the expected  map. Is the library not loaded in the good part in the code ?

- [ ] when this bug is fixed announce on La décadanse Facebook page this feature

**Comment by MarkJaroski** [comment]
I can have a look at this one, if you like.

**Comment by agilare** [comment]
Great :-) You can passe this issue to _dev_ column in the [project 3.3](https://github.com/agilare/ladecadanse/projects/3) and assign it to you

**Comment by MarkJaroski** [comment]
OK. Will do. Thanks. I plan to work on it for a bit tomorrow.

**Comment by MarkJaroski** [comment]
OK, so I have my dev environment set up, and La Decadanse working on my laptop, and all of the necessary Google API keys.

It looks like this was developed against an earlier version of the API, so I'll just start out with updating it to the newest version.
